---
title: "NB Whaling Museum Whaler Database"
author: "Marianna Foos"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    theme: journal
    toc: true
    css: "RLadies.css"
    code_folding: show
params:
  color: "purple"
---

```{r globals, message=FALSE, echo=FALSE}
library(dplyr)
library(ggplot2)

knitr::opts_chunk$set(fig.width = 9, fig.height = 7)
crewlist <- read.table("whalemenDB_cleaned_again.tsv", sep = "\t", header = TRUE)
```

```{r clean, echo=FALSE}
crewlist$ApproximateDeparture <- as.Date(crewlist$ApproximateDeparture, format = "%m/%d/%Y")
crewlist$departYear <- format(crewlist$ApproximateDeparture, "%Y")
```

### How did whaling wax and wane over the century?
```{r year-plot, echo=FALSE}
ggplot(crewlist %>% filter(!is.na(departYear)), aes(x = as.numeric(departYear))) + 
  geom_bar(fill = params$color) + 
  ggtitle("New Bedford/Fairhaven Whaleship Departures, 1809-1927") +
  theme(axis.text.x = element_text(angle=45, size=10, hjust = 1)) +
  scale_x_continuous(name = "Departure Year", breaks = seq(min(crewlist$departYear, na.rm = T), max(crewlist$departYear, na.rm = T), 5))
```

---

### Which ships made the most voyages? How noisy is this data?
```{r top-table, echo=FALSE}
voyages <- crewlist %>% 
  select(Vessel, ApproximateDeparture) %>% 
  unique() %>% 
  group_by(Vessel) %>% 
  tally() %>%
  arrange(desc(n)) %>%
  head(20)

knitr::kable(voyages, caption = "Voyages Per Vessel")
cat("\n")
```

```{r ref.label="globals", eval=FALSE}
```

```{r ref.label="clean", eval=FALSE}
```

```{r ref.label="year-plot", eval=FALSE}
```

```{r ref.label="top-table", eval=FALSE}
```

Last rendered: `r Sys.time()`
